[Tests]
  [./duplicate_objects]
    # Test error when two outputs with the same name are created (two blocks)
    type = RunException
    input = duplicate_outputs.i
    expect_err = "An output object named 'exodus' already exists"
  [../]
  [./duplicate_output_files]
    # Test error when two outputs with the same name are created (two blocks)
    type = RunException
    input = duplicate_output_files.i
    expect_err = 'An output file with the name, duplicate_output_files_out.e, already exists.'
  [../]
  [./none_reserved]
    # Test that the "none" keyword is actually reserved
    type = RunException
    input = none_reserved.i
    expect_err = "The name 'none' is a reserved name for output objects"
  [../]
  [./all_reserved]
    # Test that the "all" keyword is actually reserved
    type = RunException
    input = all_reserved.i
    expect_err = "The name 'all' is a reserved name for output objects"
  [../]
[]
